services:
  build:
    build:
      context: ./src
    volumes:
      - ./:/build
      - ~/.vimrc:/root/.vimrc:ro
    environment:
      - BUILD_ONCE
      - TERM

  serve:
    image: caddy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web:/etc/caddy:ro
    environment:
      - SERVER_ADDRESS
      - SERVER_NAME
